---
- name: Install dependencies 
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Install conmon and podman 
      yum:
        name:
          - conmon
          - podman
        state: present
    - name: Install Kubernetes python libraries
      pip:
        name:
          - kubernetes
  tags:
    - install_requirements

- name: Install collection requirements
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - ansible.builtin.command: 
        cmd: ansible-galaxy install -r collections/requirements.yml
  tags: 
    - install_requirements

- name: Run playbook
  hosts: localhost
  become: yes
  gather_facts: false
  vars_files:
    - vars/vars.yml
  roles:
    - role: acc-install
  tags:
    - install_acc
