---
#- name: Run requirements
#  hosts: localhost
#  become: yes
#  tasks:
#    - name: Install required system packages
#      apt: name={{ item }} state=latest update_cache=yes
#      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
#
#    - name: Add Docker GPG apt Key
#      apt_key:
#        url: https://download.docker.com/linux/ubuntu/gpg
#        state: present
#
#    - name: Add Docker Repository
#      apt_repository:
#        repo: deb https://download.docker.com/linux/ubuntu bionic stable
#        state: present
#
#    - name: Update apt and install docker-ce
#      apt: update_cache=yes name=docker-ce state=latest

- name: Install collection requirements
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - ansible.builtin.command: 
        cmd: ansible-galaxy install -r collections/requirements.yml
  tags: 
    - install_requirements

- name: Run playbook
  hosts: localhost
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - role: acc-install
  tags:
    - install_acc
