- name: Create a snapshot class for Trident
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshotClass
      metadata:
        name: csi-snapclass
      driver: csi.trident.netapp.io
      deletionPolicy: Delete
