- block:
  - name: Create secret with docker creds
    kubernetes.core.k8s:
      state: present
      resource_definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: "{{ astra_registry_secret_name }}"
          namespace: "{{ astra_namespace }}"
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ dockerconfig_encoded }}"
      kubeconfig: "{{ hosting_ocp_kubeconfig_path }}"
  rescue:
    - name: Failure
      fail:
        msg:
        - Creation of secret for registry credentials failed.
        - Possible troubleshooting steps - 
        - 1. Check if the kubeconfig is correct and the cluster is reachable
        - 2. Ensure there are no resources remaining from previous failed installs.
        - 3. Check if variables defined adhere to the guidelines and are correct.

