apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  accountName: "Example"
  astraVersion: "21.08.65"
  astraAddress: "astra.example.com"
  autoSupport:
    enrolled: true
  email: "admin@example.com"
  firstName: "SRE"
  lastName: "Admin"
  imageRegistry:
    name: "example.registry/astra"
    secret: "astra-registry-cred"
  storageClass: "ontap-gold"
  volumeReclaimPolicy: "Retain"
  astraResourcesScaler: "Default"
